### ISSUE TITLE
Flutter updates doesn't include hotfixes to the stable channel

### ISSUE THREAD

**Issue by uSlashVlad** [vladyslav-ts/ruzz#1]
Flutter updates only include feature updates in stable channel:
<img src="https://user-images.githubusercontent.com/37776977/202894767-ad2e8d2d-3ae2-499a-9b9b-10e662f143d9.png" width=300>

Flutter has changes in addition to feature updates: [Hotfixes to the Stable Channel](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel). They also very important and it would be nice to show them too.

Also here is no major updates (no versions 1 and 2), it would be nice to have all updates anyway

**Comment by vlts1** [comment]
Did not add these 2 since they lacked docs and if remember correctly were deleted from the Flutter website. I was able to find some docs for 3.1, which is very minor and does not change anything; however, since some people asked I still added it and marked as "cherrypick." For 3.2 no docs exist publicly, and there is no download link. Not sure if it ever came out publicly. 

Initially I decided to not add hot fixes as the point of the app is to give users insights on new features and changes, and hot fixes would simply stack the feed without giving any information, except the updated version number. It might be an option in the future, but for now I'll keep it as initially designed.
